"""
Chat page — conversational interface for interacting with the active paper.

IMPORTANT: This module contains NO real RAG logic. `_mock_generate_response`
simulates what Module 8/9 will implement: retrieval + LLM generation +
streaming. It exists purely to validate the chat UX (message flow, input
box, source display) ahead of backend implementation.
"""

import streamlit as st
from app.ui.components.chat_bubble import render_chat_bubble
from app.ui.session_state import get_active_paper


def _mock_generate_response(user_message: str) -> dict:
    """
    PLACEHOLDER — simulates the RAG pipeline's response.

    Module 8 (RAG Pipeline) will replace this with real retrieval +
    LLM generation. Module 9 will add streaming. Module 10 will
    populate real `sources`.
    """
    return {
        "content": (
            "This is a placeholder response. The real answer will be "
            "generated by the RAG pipeline (retrieval + LLM) in Module 8."
        ),
        "sources": [
            {"paper": "example_paper.pdf", "page": 3, "chunk_excerpt": "Example retrieved excerpt..."}
        ],
    }


def render_chat_page() -> None:
    """Render the Chat page: message history + input box."""
    st.header("💬 Chat with Your Paper")

    active_paper = get_active_paper() or st.session_state.get("_active_paper_cache")
    if active_paper is None:
        st.warning("⚠️ No paper selected. Please upload or select a paper first.")
        if st.button("Go to Upload Page"):
            st.session_state["active_page"] = "Upload"
            st.rerun()
        return

    st.caption(f"Chatting with: **{active_paper['filename']}**")
    st.divider()

    # Render existing chat history
    chat_container = st.container()
    with chat_container:
        for message in st.session_state["chat_history"]:
            render_chat_bubble(
                role=message["role"],
                content=message["content"],
                sources=message.get("sources"),
            )

    # Chat input
    user_message = st.chat_input("Ask a question about this paper...")
    if user_message:
        st.session_state["chat_history"].append({"role": "user", "content": user_message})

        with st.spinner("Thinking..."):
            # NOTE: real generation happens in Module 8/9.
            response = _mock_generate_response(user_message)

        st.session_state["chat_history"].append({
            "role": "assistant",
            "content": response["content"],
            "sources": response["sources"],
        })
        st.rerun()

    if st.session_state["chat_history"]:
        if st.button("🗑️ Clear Chat History"):
            st.session_state["chat_history"] = []
            st.rerun()